project_id = "xbwaphzntaxmdfzfsmvt"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
tenants = [
  { name = "realtime", db_name = "postgres", db_host = "localhost", db_port = 5432, ip_version = "ipv4" },
]

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
email_double_confirm = true
enable_signup = true
enable_anonymous_users = false

[auth.email]
enable_confirmations = false

[edge_runtime]
enabled = true
port = 54322

[functions.get-google-maps-key]
verify_jwt = false