
import React from 'react';
import { TripPlan } from '../../services/planning/TripPlanBuilder';
import PDFDaySegmentCard from './PDFDaySegmentCard';
import PDFLogo from './components/PDFLogo';

interface PDFContentRendererProps {
  tripPlan: TripPlan;
  tripStartDate?: Date;
  exportOptions: any;
  shareUrl?: string;
}

const PDFContentRenderer: React.FC<PDFContentRendererProps> = ({
  tripPlan,
  tripStartDate,
  exportOptions,
  shareUrl
}) => {
  console.log('📄 PDFContentRenderer: Rendering PDF content with', {
    segmentsCount: tripPlan.segments?.length || 0,
    exportFormat: exportOptions.format
  });

  return (
    <div className="pdf-content bg-white min-h-screen p-8">
      {/* Header */}
      <div className="pdf-header mb-8 text-center border-b-2 border-gray-200 pb-6">
        <PDFLogo showFallback={true} />
        <h1 className="text-3xl font-bold text-blue-800 mt-4">
          {exportOptions.title || `Route 66 Trip: ${tripPlan.startCity} to ${tripPlan.endCity}`}
        </h1>
        <p className="text-lg text-gray-600 mt-2">
          {tripPlan.totalDays} days • {Math.round(tripPlan.totalDistance)} miles
        </p>
        <p className="text-sm text-gray-500 mt-2">
          Generated on {new Date().toLocaleDateString()}
        </p>
      </div>

      {/* Trip Overview */}
      <div className="pdf-overview mb-8 p-4 bg-blue-50 rounded border border-blue-200">
        <h2 className="text-xl font-bold text-blue-800 mb-3">Trip Overview</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
          <div className="text-center">
            <div className="font-bold text-blue-700">Start</div>
            <div className="text-gray-700">{tripPlan.startCity}</div>
          </div>
          <div className="text-center">
            <div className="font-bold text-blue-700">End</div>
            <div className="text-gray-700">{tripPlan.endCity}</div>
          </div>
          <div className="text-center">
            <div className="font-bold text-blue-700">Duration</div>
            <div className="text-gray-700">{tripPlan.totalDays} days</div>
          </div>
          <div className="text-center">
            <div className="font-bold text-blue-700">Distance</div>
            <div className="text-gray-700">{Math.round(tripPlan.totalDistance)} miles</div>
          </div>
        </div>
      </div>

      {/* Daily Segments */}
      <div className="pdf-segments">
        <h2 className="text-xl font-bold text-blue-800 mb-6">Daily Itinerary</h2>
        {tripPlan.segments && tripPlan.segments.map((segment, index) => (
          <PDFDaySegmentCard
            key={segment.day}
            segment={segment}
            tripStartDate={tripStartDate}
            cardIndex={index}
            exportFormat={exportOptions.format}
          />
        ))}
      </div>

      {/* Footer */}
      <div className="pdf-footer mt-8 pt-6 border-t-2 border-gray-200 text-center text-sm text-gray-600">
        <p>Generated by Ramble 66 Route Planner</p>
        {shareUrl && exportOptions.includeQRCode && (
          <p className="mt-2">Visit the live version: {shareUrl}</p>
        )}
        {exportOptions.watermark && (
          <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-gray-200 text-6xl font-bold rotate-45 pointer-events-none opacity-30">
            {exportOptions.watermark}
          </div>
        )}
      </div>
    </div>
  );
};

export default PDFContentRenderer;
