
import React from 'react';
import { format } from 'date-fns';
import { TripPlan } from '../../services/planning/TripPlanBuilder';
import LogoImage from '../../../shared/LogoImage';

interface PDFEnhancedHeaderProps {
  title: string;
  tripPlan: TripPlan;
  tripStartDate?: Date;
  logoUrl?: string;
}

const PDFEnhancedHeader: React.FC<PDFEnhancedHeaderProps> = ({
  title,
  tripPlan,
  tripStartDate,
  logoUrl
}) => {
  return (
    <div className="pdf-header no-page-break mb-8 text-center border-b-4 border-route66-primary pb-6">
      {/* Centered Logo Section */}
      <div className="flex justify-center items-center mb-6">
        <div className="logo-container text-center">
          <LogoImage 
            className="h-16 w-auto max-w-[200px] object-contain mx-auto"
            alt="Ramble 66 - Route 66 Trip Planner"
          />
          <div className="text-xs text-route66-text-secondary font-medium tracking-wider mt-2 text-center">
            ROUTE 66 TRIP PLANNER
          </div>
        </div>
      </div>
      
      {/* Trip Title with Enhanced Route 66 Styling */}
      <div className="mb-6 p-6 bg-gradient-to-r from-route66-cream via-route66-vintage-beige to-route66-cream rounded-lg border-4 border-route66-vintage-brown shadow-lg">
        <h1 className="text-4xl font-bold text-route66-vintage-red mb-3 font-route66 tracking-wide">
          {title}
        </h1>
        
        {/* Trip Subtitle with Historic Route 66 Styling */}
        <div className="text-xl text-route66-vintage-brown font-travel mb-3 italic">
          {tripPlan.totalDays} Day Historic Route 66 Journey • {Math.round(tripPlan.totalDistance)} Miles of Adventure
        </div>
        
        {/* Trip Route Description with Vintage Elements */}
        <div className="text-lg text-route66-navy font-semibold bg-route66-vintage-yellow px-4 py-2 rounded-full inline-block border-2 border-route66-tan">
          🛣️ From {tripPlan.startCity} to {tripPlan.endCity} on America's Mother Road
        </div>
      </div>
      
      {/* Trip Dates with Enhanced Styling */}
      {tripStartDate && (
        <div className="mb-6 p-4 bg-route66-vintage-yellow rounded-lg border-2 border-route66-tan shadow-md">
          <div className="text-lg font-bold text-route66-navy mb-2 font-route66">
            📅 Your Journey Timeline
          </div>
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div className="bg-white p-3 rounded border border-route66-border">
              <div className="font-semibold text-route66-primary mb-1">🚗 Start Date</div>
              <div className="text-route66-vintage-brown font-medium">
                {format(tripStartDate, 'EEEE, MMMM d, yyyy')}
              </div>
            </div>
            <div className="bg-white p-3 rounded border border-route66-border">
              <div className="font-semibold text-route66-primary mb-1">🏁 End Date</div>
              <div className="text-route66-vintage-brown font-medium">
                {format(
                  new Date(tripStartDate.getTime() + (tripPlan.totalDays - 1) * 24 * 60 * 60 * 1000),
                  'EEEE, MMMM d, yyyy'
                )}
              </div>
            </div>
          </div>
        </div>
      )}
      
      {/* Generation Info with Enhanced Route 66 Branding */}
      <div className="text-sm text-route66-vintage-brown bg-route66-cream rounded-lg p-4 border-2 border-route66-tan shadow-sm">
        <div className="font-bold text-route66-primary mb-2 text-base">
          📋 Generated by RAMBLE 66 Historic Route Planner
        </div>
        <div className="text-xs">
          Your personalized itinerary created on {format(new Date(), 'MMMM d, yyyy')} • Visit us at ramble66.com
        </div>
        <div className="mt-2 text-xs italic text-route66-vintage-red">
          "Get your kicks on Route 66!" - Experience America's most famous highway
        </div>
      </div>
    </div>
  );
};

export default PDFEnhancedHeader;
