
import React from 'react';
import { format } from 'date-fns';
import { TripPlan } from '../../services/planning/TripPlanBuilder';
import RambleBranding from '../../../shared/RambleBranding';

interface PDFHeaderProps {
  title: string;
  tripPlan: TripPlan;
  tripStartDate?: Date;
}

const PDFHeader: React.FC<PDFHeaderProps> = ({
  title,
  tripPlan,
  tripStartDate
}) => {
  return (
    <div className="pdf-header no-page-break mb-8 text-center border-b-2 border-route66-primary pb-6">
      {/* Enhanced Ramble 66 Branding */}
      <div className="flex justify-center mb-6">
        <RambleBranding variant="full" size="lg" />
      </div>
      
      {/* Trip Title with Enhanced Styling */}
      <div className="mb-4 p-4 bg-gradient-to-r from-route66-cream to-route66-vintage-beige rounded-lg border-2 border-route66-vintage-brown">
        <h1 className="text-3xl font-bold text-route66-vintage-red mb-2 font-route66">
          {title}
        </h1>
        
        {/* Trip Subtitle with Route 66 Styling */}
        <div className="text-lg text-route66-vintage-brown font-travel mb-2">
          {tripPlan.totalDays} Day Route 66 Adventure • {Math.round(tripPlan.totalDistance)} Historic Miles
        </div>
        
        {/* Trip Route Description */}
        <div className="text-sm text-route66-navy font-medium">
          🛣️ From {tripPlan.startCity} to {tripPlan.endCity} along America's Main Street
        </div>
      </div>
      
      {/* Trip Dates with Enhanced Styling */}
      {tripStartDate && (
        <div className="mb-4 p-3 bg-route66-vintage-yellow rounded border border-route66-tan">
          <div className="text-sm font-semibold text-route66-navy mb-1">
            📅 Your Journey Dates
          </div>
          <div className="text-sm text-route66-vintage-brown">
            <strong>Departure:</strong> {format(tripStartDate, 'EEEE, MMMM d, yyyy')}
          </div>
          <div className="text-sm text-route66-vintage-brown">
            <strong>Return:</strong> {format(
              new Date(tripStartDate.getTime() + (tripPlan.totalDays - 1) * 24 * 60 * 60 * 1000),
              'EEEE, MMMM d, yyyy'
            )}
          </div>
        </div>
      )}
      
      {/* Generation Info with Branding */}
      <div className="text-xs text-gray-500 bg-gray-50 rounded p-2 border">
        <div className="font-medium text-route66-primary mb-1">
          Generated by RAMBLE 66 Route Planner
        </div>
        <div>
          Created on {format(new Date(), 'MMMM d, yyyy')} • www.ramble66.com
        </div>
      </div>
    </div>
  );
};

export default PDFHeader;
